#!/usr/bin/env bash
#answer to quiz
It is a protocol that is transferring data in a fast way and might loss data along in the process
It is a protocol that is transferring data in a slow way but surely
May I increase the rate at which I am sending you boxes?