#!/usr/bin/env bash
#print based on fizz, fizzBuss and Buzz
i=1
while [ $i -lt 100 ]
do
	echo "$1"
	if [ $((i % 3)) -eq 0 ] &&  [ $((i % 5)) -eq 0 ]; then
		echo "Fizz Buzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
