#!/usr/bin/env bash
#prints using while loop and also Hi
a=10
string="Best School"
b=0
c=9

while [ $b -lt $a ]
do
	echo "$string"
	((b++))
    if [ $b -eq $c ]
    then
        echo "Hi"
    fi
done
