#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:

   #displays bad luck for the 4th loop iteration
   #displays good luck for the 8th loop iteration
   #displays Best School for the other iterations

i=0

while [ $i -lt 10 ]
do
   if [ $i -eq 9 ]
      then
          echo "Hi"
      fi
   echo "Best School"
   i=$(( $i + 1))
done

