#!/usr/bin/env bash
#print time
min=1
hour=0
while [ $hour -lt 13 ]
do
    echo "Hour: $hour "
    while [ $min -lt 60 ]
    do
        echo "$min"
        ((min++))   
    done
    ((hour++))
    min=1
done
