#!/usr/bin/env bash
#print time
min=1
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour "
    while [ $min -lt 59 ]
    do
        echo "$min"
        ((min++))   
    done
    min=1
    ((hour++))
done
